<?php
declare(strict_types=1);
/**
 * Lumora Gallery — Configuration
 *
 * This file is generated by the installer (/install/).
 * Copy to config.php and fill in your values if you are setting up manually.
 *
 * DO NOT expose this file publicly; it contains your database credentials.
 *
 * @package    LumoraGallery
 * @subpackage Core
 * @author     Ariane
 * @copyright  Copyright (c) 2026 Ariane
 * @license    GPL-3.0-or-later <https://www.gnu.org/licenses/gpl-3.0>
 * @link       https://coding.unloved-heart.net/scripts/lumoragallery
 * @source     https://github.com/intothisshadow/LumoraGallery
 * @since      1.0.0
 */

// ── Database ──────────────────────────────────────────────────────────────────
define('DB_HOST',    'localhost');         // MySQL/MariaDB hostname
define('DB_NAME',    'your_database');    // Database name
define('DB_USER',    'your_user');        // Database username
define('DB_PASS',    'your_password');    // Database password
define('DB_PREFIX',  'lum_');             // Table prefix — the installer generates a unique value
                                          // in the format lum_XXXXXXXX_ (e.g. lum_3f9a12b4_).
                                          // Only letters, digits, and underscores are allowed.
                                          // Existing installations using lum_ continue to work unchanged.
define('DB_CHARSET', 'utf8mb4');          // Leave as utf8mb4

// ── Installation flag ─────────────────────────────────────────────────────────
// Set to true only after the installer has completed successfully.
define('LUMORA_INSTALLED', true);
