<?php
declare(strict_types=1);
/**
 * Lumora Gallery — Cache Header Service
 *
 * LiteSpeed/Apache-compatible browser caching for static assets, and optional
 * LiteSpeed Cache (LSCache) purge integration (LG-033).
 *
 * Images, thumbnails, and theme CSS/JS are served directly by the web server
 * (there is no PHP script in the request path for any of them), so Lumora
 * cannot set their Cache-Control/Expires headers with PHP's header() — those
 * headers have to come from the web server itself. This class manages a
 * clearly-delimited, additive block in the site's root .htaccess containing
 * mod_expires/mod_headers directives that both Apache and LiteSpeed read
 * identically, leaving any content outside that block untouched. nginx and
 * Caddy do not read .htaccess at all; those admins configure caching at the
 * server level instead, which is unaffected either way.
 *
 * A second, independent managed block (recommendedPageCacheRules() and
 * friends) opt-in enables actual LiteSpeed Cache page caching via
 * `CacheEnable` — for hosts where server-level cache rules aren't available
 * to the admin (e.g. some DirectAdmin/shared-hosting LiteSpeed setups with
 * no WebAdmin console access). LiteSpeed-only; a no-op block on any other
 * server. Both blocks can be installed independently and removed
 * independently.
 *
 * @package    LumoraGallery
 * @subpackage Cache
 * @author     Ariane
 * @copyright  Copyright (c) 2026 Ariane
 * @license    GPL-3.0-or-later <https://www.gnu.org/licenses/gpl-3.0>
 * @link       https://coding.unloved-heart.net/scripts/lumoragallery
 * @source     https://github.com/intothisshadow/LumoraGallery
 * @since      1.12.0
 * @see        ServerEnvironmentService Detects the LiteSpeed environment this class checks.
 */

if (!defined('LUMORA_ENTRY')) exit('Direct access denied.');

class CacheHeaderService
{
    private const MARKER_START = '# BEGIN Lumora Cache Headers';
    private const MARKER_END   = '# END Lumora Cache Headers';

    private const PAGE_MARKER_START = '# BEGIN Lumora Page Cache';
    private const PAGE_MARKER_END   = '# END Lumora Page Cache';

    /** Minimum/maximum accepted page-cache TTL, in seconds (1 s – 24 h). */
    private const PAGE_CACHE_TTL_MIN = 1;
    private const PAGE_CACHE_TTL_MAX = 86400;

    /** Absolute path to the .htaccess file this service manages. */
    public static function htaccessPath(): string
    {
        return LUMORA_ROOT . '.htaccess';
    }

    /**
     * The managed cache-control block, ready to insert into an .htaccess
     * file. Images/fonts get a long-lived immutable Cache-Control (filenames
     * already change on re-upload, so there's nothing to invalidate); CSS/JS
     * get a shorter max-age since theme files can change without a filename
     * change.
     */
    public static function recommendedRules(): string
    {
        return self::MARKER_START . "\n"
            . "# Generated by Lumora Gallery (LG-033) — safe to remove from the admin\n"
            . "# Installation page. Directives below are read identically by Apache\n"
            . "# (mod_expires, mod_headers) and LiteSpeed/OpenLiteSpeed.\n"
            . "<IfModule mod_expires.c>\n"
            . "  ExpiresActive On\n"
            . "  ExpiresByType image/jpeg              \"access plus 1 year\"\n"
            . "  ExpiresByType image/png               \"access plus 1 year\"\n"
            . "  ExpiresByType image/gif               \"access plus 1 year\"\n"
            . "  ExpiresByType image/webp              \"access plus 1 year\"\n"
            . "  ExpiresByType image/avif              \"access plus 1 year\"\n"
            . "  ExpiresByType font/woff2              \"access plus 1 year\"\n"
            . "  ExpiresByType font/woff               \"access plus 1 year\"\n"
            . "  ExpiresByType text/css                \"access plus 1 month\"\n"
            . "  ExpiresByType application/javascript  \"access plus 1 month\"\n"
            . "</IfModule>\n"
            . "<IfModule mod_headers.c>\n"
            . "  <FilesMatch \"\\.(jpe?g|png|gif|webp|avif|woff2?)$\">\n"
            . "    Header set Cache-Control \"public, max-age=31536000, immutable\"\n"
            . "  </FilesMatch>\n"
            . "  <FilesMatch \"\\.(css|js)$\">\n"
            . "    Header set Cache-Control \"public, max-age=2592000\"\n"
            . "  </FilesMatch>\n"
            . "</IfModule>\n"
            . self::MARKER_END;
    }

    /**
     * Current on-disk state of the managed static-asset cache block.
     *
     * @param string|null $path Override the target file — used by tests so
     *                          they never touch the real project .htaccess.
     * @return array{path: string, exists: bool, managed_present: bool}
     */
    public static function status(?string $path = null): array
    {
        return self::blockStatus($path ?? self::htaccessPath(), self::MARKER_START);
    }

    /**
     * Write (or update) the managed static-asset cache block in the target
     * .htaccess file. Idempotent — re-running it replaces only the previous
     * managed block (identified by its markers) rather than duplicating it,
     * and never touches any content outside those markers.
     *
     * @param string|null $path Override the target file — used by tests so
     *                          they never touch the real project .htaccess.
     * @return array{success: bool, error: string}
     */
    public static function writeRules(?string $path = null): array
    {
        return self::writeBlock(
            $path ?? self::htaccessPath(),
            self::MARKER_START,
            self::MARKER_END,
            self::recommendedRules()
        );
    }

    /**
     * Remove the managed static-asset cache block from the target .htaccess
     * file, leaving any other content untouched. A no-op (success) if the
     * file or block doesn't exist.
     *
     * @param string|null $path Override the target file — used by tests so
     *                          they never touch the real project .htaccess.
     * @return array{success: bool, error: string}
     */
    public static function removeRules(?string $path = null): array
    {
        return self::removeBlock($path ?? self::htaccessPath(), self::MARKER_START, self::MARKER_END);
    }

    // ── Page cache (LiteSpeed Cache, opt-in) ─────────────────────────────────

    /**
     * The managed LiteSpeed page-cache block, ready to insert into an
     * .htaccess file. LiteSpeed-only (`<IfModule LiteSpeed>`) — silently
     * ignored on Apache without the LiteSpeed module, and irrelevant to
     * nginx/Caddy, which don't read .htaccess at all.
     *
     * Deliberately does not attempt to exclude specific paths itself: public
     * pages already send no session cookie for anonymous visitors (see
     * include/bootstrap.php's lazy session start), and LSCache's own default
     * behaviour already skips caching any response that does carry one — the
     * admin panel (always-sessioned) and any logged-in visit are excluded by
     * that alone, with admin/.htaccess's `CacheLookup off` as a second,
     * explicit layer specifically for /admin/.
     */
    public static function recommendedPageCacheRules(int $ttlSeconds): string
    {
        $ttl = max(self::PAGE_CACHE_TTL_MIN, min(self::PAGE_CACHE_TTL_MAX, $ttlSeconds));

        return self::PAGE_MARKER_START . "\n"
            . "# Generated by Lumora Gallery (LG-033 follow-up) — safe to remove from\n"
            . "# the admin Installation page. LiteSpeed-only; ignored elsewhere.\n"
            . "<IfModule LiteSpeed>\n"
            . "  CacheLookup on\n"
            . "  CacheEnable public /\n"
            . "  TTL {$ttl}\n"
            . "</IfModule>\n"
            . self::PAGE_MARKER_END;
    }

    /**
     * Current on-disk state of the managed page-cache block.
     *
     * @param string|null $path Override the target file — used by tests so
     *                          they never touch the real project .htaccess.
     * @return array{path: string, exists: bool, managed_present: bool}
     */
    public static function pageCacheStatus(?string $path = null): array
    {
        return self::blockStatus($path ?? self::htaccessPath(), self::PAGE_MARKER_START);
    }

    /**
     * Write (or update) the managed page-cache block in the target
     * .htaccess file. Persisting the TTL to the `litespeed_page_cache_ttl`
     * config key is the caller's responsibility (admin/installation.php) —
     * this method only touches the filesystem, so it stays usable without a
     * database connection, matching every other method in this class.
     *
     * @param string|null $path Override the target file — used by tests so
     *                          they never touch the real project .htaccess.
     * @return array{success: bool, error: string}
     */
    public static function writePageCacheRules(int $ttlSeconds, ?string $path = null): array
    {
        $ttl = max(self::PAGE_CACHE_TTL_MIN, min(self::PAGE_CACHE_TTL_MAX, $ttlSeconds));

        return self::writeBlock(
            $path ?? self::htaccessPath(),
            self::PAGE_MARKER_START,
            self::PAGE_MARKER_END,
            self::recommendedPageCacheRules($ttl)
        );
    }

    /**
     * Remove the managed page-cache block from the target .htaccess file.
     * Resetting the `litespeed_page_cache_ttl` config key is the caller's
     * responsibility — see writePageCacheRules().
     *
     * @param string|null $path Override the target file — used by tests so
     *                          they never touch the real project .htaccess.
     * @return array{success: bool, error: string}
     */
    public static function removePageCacheRules(?string $path = null): array
    {
        return self::removeBlock($path ?? self::htaccessPath(), self::PAGE_MARKER_START, self::PAGE_MARKER_END);
    }

    // ── Shared managed-block helpers ─────────────────────────────────────────

    /** @return array{path: string, exists: bool, managed_present: bool} */
    private static function blockStatus(string $path, string $startMarker): array
    {
        $exists  = is_file($path);
        $managed = $exists && str_contains((string) file_get_contents($path), $startMarker);

        return ['path' => $path, 'exists' => $exists, 'managed_present' => $managed];
    }

    /** @return array{success: bool, error: string} */
    private static function writeBlock(string $path, string $startMarker, string $endMarker, string $block): array
    {
        $existing = is_file($path) ? (string) file_get_contents($path) : '';

        if (str_contains($existing, $startMarker) && str_contains($existing, $endMarker)) {
            $pattern = '/' . preg_quote($startMarker, '/') . '.*?' . preg_quote($endMarker, '/') . '/s';
            $updated = (string) preg_replace($pattern, $block, $existing);
        } else {
            $updated = rtrim($existing) . ($existing !== '' ? "\n\n" : '') . $block . "\n";
        }

        if (@file_put_contents($path, $updated) === false) {
            return ['success' => false, 'error' => 'Could not write to ' . $path . ' — check file permissions.'];
        }

        return ['success' => true, 'error' => ''];
    }

    /** @return array{success: bool, error: string} */
    private static function removeBlock(string $path, string $startMarker, string $endMarker): array
    {
        if (!is_file($path)) {
            return ['success' => true, 'error' => ''];
        }

        $existing = (string) file_get_contents($path);
        $pattern  = '/\n?' . preg_quote($startMarker, '/') . '.*?' . preg_quote($endMarker, '/') . '\n?/s';
        $updated  = (string) preg_replace($pattern, '', $existing);

        if (@file_put_contents($path, $updated) === false) {
            return ['success' => false, 'error' => 'Could not write to ' . $path . ' — check file permissions.'];
        }

        return ['success' => true, 'error' => ''];
    }

    // ── LiteSpeed Cache purge ────────────────────────────────────────────────

    /**
     * Send an LSCache purge-all header for the current response, if — and
     * only if — all of the following hold:
     *   - Response headers have not already been sent.
     *   - The `litespeed_cache_purge` config toggle is enabled (opt-in,
     *     default off — admin/config.php).
     *   - The current server is detected as LiteSpeed/OpenLiteSpeed.
     *
     * A complete no-op on Apache, nginx, Caddy, or with the toggle off, so
     * it is safe to call unconditionally after any content-changing action.
     */
    public static function purgeLiteSpeedCache(): void
    {
        if (headers_sent()) {
            return;
        }

        if (LumoraConfig::get('litespeed_cache_purge', '0') !== '1') {
            return;
        }

        if (!ServerEnvironmentService::detect()['is_litespeed']) {
            return;
        }

        header('X-LiteSpeed-Purge: *');
    }
}
